# Generated by Django 4.2.23 on 2025-06-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='fall_watering_interval_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='indoor_watering_interval_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='location',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='indoor', max_length=10),
        ),
        migrations.AddField(
            model_name='plant',
            name='outdoor_watering_interval_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='spring_watering_interval_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='summer_watering_interval_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='winter_watering_interval_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planttype',
            name='default_fall_watering_interval_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planttype',
            name='default_indoor_watering_interval_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planttype',
            name='default_outdoor_watering_interval_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planttype',
            name='default_spring_watering_interval_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planttype',
            name='default_summer_watering_interval_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planttype',
            name='default_winter_watering_interval_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
