# Generated by Django 4.2.23 on 2026-02-27

import secrets

from django.db import migrations, models
import plants.models


def populate_device_api_keys(apps, schema_editor):
    Device = apps.get_model('plants', 'Device')
    for device in Device.objects.filter(api_key__isnull=True):
        key = secrets.token_hex(24)
        while Device.objects.filter(api_key=key).exists():
            key = secrets.token_hex(24)
        device.api_key = key
        device.save(update_fields=['api_key'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_fall_watering_interval_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='api_key',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.RunPython(populate_device_api_keys, noop_reverse),
        migrations.AlterField(
            model_name='device',
            name='api_key',
            field=models.CharField(default=plants.models.generate_device_api_key, editable=False, max_length=64, unique=True),
        ),
    ]
