# Generated by Django 4.2.23 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_device_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='soil_moisture_wet_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='soil_moisture_wet_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
