# Generated by Django 4.2.23 on 2026-02-27

from django.db import migrations, models
from django.utils import timezone


def initialize_retry_schedule(apps, schema_editor):
    Notification = apps.get_model('plants', 'Notification')
    Notification.objects.filter(sent=False, next_attempt_at__isnull=True).update(next_attempt_at=timezone.now())


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_garden_soil_moisture_wet_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(initialize_retry_schedule, noop_reverse),
    ]
