# Generated by Django 4.2.28 on 2026-02-27 22:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_notification_retry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='automation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='humidity_high_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='light_low_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='soil_moisture_dry_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='individual_repotting_interval_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='individual_requires_pre_watering',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_repotted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='pre_fertilization_water_gap_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planttype',
            name='default_pre_fertilization_water_gap_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='planttype',
            name='default_repotting_interval_days',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='planttype',
            name='default_requires_pre_watering',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='calendarevent',
            unique_together={('plant', 'event_type', 'date')},
        ),
        migrations.CreateModel(
            name='PlantStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('flowering', 'Flowering'), ('dormant', 'Dormant'), ('repotted', 'Repotted'), ('stressed', 'Stressed'), ('pest', 'Pest'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='plants.plant')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('water_pump_on', 'Water Pump On'), ('grow_light_on', 'Grow Light On'), ('ventilation_on', 'Ventilation On'), ('custom', 'Custom')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='plants.device')),
            ],
        ),
    ]
