# Generated by Django 4.2.28 on 2026-02-27 22:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_garden_automation_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PestDiseaseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('profile_type', models.CharField(choices=[('pest', 'Pest'), ('disease', 'Disease')], max_length=20)),
                ('symptoms', models.TextField()),
                ('default_treatment_plan', models.TextField(blank=True)),
                ('follow_up_interval_days', models.IntegerField(default=7)),
                ('severity_hint', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='garden',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='usda_hardiness_zone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='plant',
            name='drainage_class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='pot_volume_liters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='soil_moisture_critical_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='substrate_type',
            field=models.CharField(blank=True, choices=[('soil', 'Soil'), ('coco', 'Coco Coir'), ('hydro', 'Hydroponic'), ('mix', 'Soilless Mix')], max_length=20),
        ),
        migrations.AddField(
            model_name='plant',
            name='sun_exposure_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planttype',
            name='cultivar',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='planttype',
            name='default_substrate_type',
            field=models.CharField(choices=[('soil', 'Soil'), ('coco', 'Coco Coir'), ('hydro', 'Hydroponic'), ('mix', 'Soilless Mix')], default='soil', max_length=20),
        ),
        migrations.AddField(
            model_name='planttype',
            name='moisture_preference',
            field=models.CharField(choices=[('dry', 'Dry'), ('balanced', 'Balanced'), ('moist', 'Moist')], default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='planttype',
            name='preferred_usda_zone_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planttype',
            name='preferred_usda_zone_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planttype',
            name='profile_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planttype',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='PestIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('detected_on', models.DateField(default=django.utils.timezone.now)),
                ('symptoms_observed', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_incidents', to='plants.plant')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.pestdiseaseprofile')),
            ],
        ),
    ]
