# Generated by Django 4.2.28 on 2026-02-27 23:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_pestdiseaseprofile_garden_latitude_garden_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceaction',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviceaction',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deviceaction',
            name='next_attempt_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='SensorIngestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_records', to='plants.device')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_records', to='plants.sensorreading')),
            ],
            options={
                'unique_together': {('device', 'idempotency_key')},
            },
        ),
    ]
