# Generated by Django 4.2.28 on 2026-02-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_deviceaction_attempts_deviceaction_last_error_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deviceaction',
            index=models.Index(fields=['status', 'next_attempt_at', 'attempts'], name='plants_devi_status_35885d_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceaction',
            index=models.Index(fields=['device', 'action_type', 'status', 'created_at'], name='plants_devi_device__49083d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sent', 'next_attempt_at'], name='plants_noti_sent_c6e672_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['device', 'timestamp'], name='plants_sens_device__48c173_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['timestamp'], name='plants_sens_timesta_b2e4a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.CheckConstraint(check=models.Q(('pot_volume_liters__isnull', True), ('pot_volume_liters__gte', 0), _connector='OR'), name='plant_pot_volume_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.CheckConstraint(check=models.Q(('drainage_class__isnull', True), models.Q(('drainage_class__gte', 1), ('drainage_class__lte', 5)), _connector='OR'), name='plant_drainage_class_range'),
        ),
    ]
