# Generated by Django 4.2.28 on 2026-02-27 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_deviceaction_plants_devi_status_35885d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('scope', models.CharField(choices=[('plant', 'Plant'), ('group', 'Group')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100)),
                ('watering_interval_days', models.IntegerField(blank=True, null=True)),
                ('fertilization_interval_days', models.IntegerField(blank=True, null=True)),
                ('repotting_interval_days', models.IntegerField(blank=True, null=True)),
                ('requires_pre_watering', models.BooleanField(blank=True, null=True)),
                ('pre_fertilization_water_gap_days', models.IntegerField(blank=True, null=True)),
                ('soil_moisture_wet_threshold', models.IntegerField(blank=True, null=True)),
                ('soil_moisture_dry_threshold', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_rules', to='plants.plantgroup')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_rules', to='plants.plant')),
            ],
            options={
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['scope', 'enabled', 'priority'], name='plants_plan_scope_c0da93_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='plantcarerule',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('scope', 'plant'), ('plant__isnull', False), ('group__isnull', True)), models.Q(('scope', 'group'), ('group__isnull', False), ('plant__isnull', True)), _connector='OR'), name='care_rule_scope_target_consistency'),
        ),
    ]
